<?php
defined( 'ABSPATH' ) || exit;

/**
 * llms.txt & llms-full.txt Generator.
 *
 * Implements the https://llmstxt.org standard.
 * Serves structured, clean markdown for AI search crawlers (OpenAI, Claude, Perplexity, etc.)
 * giving LLMs a high-density, authoritative overview of the site, core pages, and top content.
 */
class VMSB_LLMS_Txt {

	const TRANSIENT_KEY      = 'vmsb_llms_txt_cache';
	const TRANSIENT_FULL_KEY = 'vmsb_llms_full_txt_cache';
	const CACHE_TTL          = 86400; // 24 hours.

	public function __construct() {
		add_action( 'init', array( $this, 'register_rewrite' ) );
		add_filter( 'query_vars', array( $this, 'register_query_vars' ) );
		add_action( 'template_redirect', array( $this, 'handle_request' ) );
		add_action( 'save_post', array( $this, 'clear_cache' ) );
	}

	public function register_rewrite() {
		add_rewrite_rule( '^llms\.txt$', 'index.php?vmsb_llms=1', 'top' );
		add_rewrite_rule( '^llms-full\.txt$', 'index.php?vmsb_llms_full=1', 'top' );
	}

	public function register_query_vars( $vars ) {
		$vars[] = 'vmsb_llms';
		$vars[] = 'vmsb_llms_full';
		return $vars;
	}

	public function handle_request() {
		$is_llms      = (int) get_query_var( 'vmsb_llms' );
		$is_llms_full = (int) get_query_var( 'vmsb_llms_full' );

		if ( ! $is_llms && ! $is_llms_full ) {
			return;
		}

		if ( ! (int) VMSB_Settings::get( 'feature_llms_txt', 1 ) ) {
			status_header( 404 );
			nocache_headers();
			exit( 'llms.txt is disabled on this site.' );
		}

		header( 'Content-Type: text/plain; charset=utf-8' );
		header( 'X-Robots-Tag: noindex, follow' );

		if ( $is_llms_full ) {
			echo $this->render_llms_full();
		} else {
			echo $this->render_llms();
		}
		exit;
	}

	public function clear_cache() {
		delete_transient( self::TRANSIENT_KEY );
		delete_transient( self::TRANSIENT_FULL_KEY );
	}

	/**
	 * Generate standard llms.txt (High level overview, key pages, and curated articles).
	 */
	public function render_llms() {
		$cached = get_transient( self::TRANSIENT_KEY );
		if ( false !== $cached && ! is_user_logged_in() ) {
			return $cached;
		}

		$brain   = new VMSB_Brain();
		$profile = $brain->profile();
		$site_name = get_bloginfo( 'name' );
		$tagline   = get_bloginfo( 'description' );
		$site_url  = home_url();

		$output  = "# {$site_name}\n\n";
		$output .= "> {$tagline}\n\n";

		if ( ! empty( $profile['description'] ) ) {
			$output .= "## About\n\n";
			$output .= trim( $profile['description'] ) . "\n\n";
		}

		if ( ! empty( $profile['services'] ) ) {
			$output .= "## Core Services & Capabilities\n\n";
			$services = is_array( $profile['services'] )
				? $profile['services']
				: preg_split( '/[\r\n,]+/', (string) $profile['services'] );
			foreach ( $services as $svc ) {
				$svc = trim( $svc );
				if ( $svc !== '' ) {
					$output .= "- " . $svc . "\n";
				}
			}
			$output .= "\n";
		}

		// Key Pages
		$output .= "## Main Sections\n\n";
		$pages = get_posts( array(
			'post_type'      => 'page',
			'post_status'    => 'publish',
			'posts_per_page' => 15,
			'orderby'        => 'menu_order title',
			'order'          => 'ASC',
		) );
		foreach ( $pages as $p ) {
			$excerpt = wp_strip_all_tags( $p->post_excerpt ?: wp_trim_words( $p->post_content, 20 ) );
			$output .= "- [{$p->post_title}](" . get_permalink( $p->ID ) . "): {$excerpt}\n";
		}
		$output .= "\n";

		// Authoritative Articles
		$output .= "## Core Articles & Knowledge Base\n\n";
		$posts = get_posts( array(
			'post_type'      => 'post',
			'post_status'    => 'publish',
			'posts_per_page' => 30,
			'orderby'        => 'date',
			'order'          => 'DESC',
		) );
		foreach ( $posts as $p ) {
			$excerpt = wp_strip_all_tags( $p->post_excerpt ?: wp_trim_words( $p->post_content, 25 ) );
			$output .= "- [{$p->post_title}](" . get_permalink( $p->ID ) . "): {$excerpt}\n";
		}
		$output .= "\n";

		// Link to full text version
		$output .= "## Full Context\n\n";
		$output .= "- [Full LLM Knowledge Feed](" . home_url( '/llms-full.txt' ) . "): Complete text content of all primary documentation and posts.\n";

		set_transient( self::TRANSIENT_KEY, $output, self::CACHE_TTL );
		return $output;
	}

	/**
	 * Generate full context markdown for deep indexing.
	 */
	public function render_llms_full() {
		$cached = get_transient( self::TRANSIENT_FULL_KEY );
		if ( false !== $cached && ! is_user_logged_in() ) {
			return $cached;
		}

		$site_name = get_bloginfo( 'name' );
		$output  = "# {$site_name} - Full Knowledge Context\n\n";
		$output .= "> Complete text context generated by VM SEO Brain for AI Retrieval and RAG.\n\n";

		$posts = get_posts( array(
			'post_type'      => array( 'page', 'post' ),
			'post_status'    => 'publish',
			'posts_per_page' => 50,
			'orderby'        => 'date',
			'order'          => 'DESC',
		) );

		foreach ( $posts as $p ) {
			$output .= "---\n\n";
			$output .= "## " . esc_html( $p->post_title ) . "\n\n";
			$output .= "URL: " . get_permalink( $p->ID ) . "\n\n";
			$clean_content = wp_strip_all_tags( strip_shortcodes( $p->post_content ) );
			$clean_content = preg_replace( "/\n{3,}/", "\n\n", trim( $clean_content ) );
			$output .= $clean_content . "\n\n";
		}

		set_transient( self::TRANSIENT_FULL_KEY, $output, self::CACHE_TTL );
		return $output;
	}
}
